### ISSUE TITLE
Https request to google returns DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by kmamal** [mcollina/undici#217]
@ronag Short reproduction

```js
const { Client } = require('undici')

const client = new Client('https://www.google.com')

client.request({ method: 'GET', path: '/' }, (error, data) => {
  if (error) {
    throw error
  }

  const { statusCode, body } = data

  if (statusCode !== 200) {
    throw new Error(`Status code ${statusCode}`)
  }

  body.pipe(process.stdout)
})
```

**Comment by ronag** [comment]
So in order to get this to work you have to do the following:

```js
  const client = new Client('https://www.google.com', {
    tls: {
      servername: 'www.google.com'
    }
  })
  t.tearDown(client.close.bind(client))
```

I'm not exactly sure how `servername` works and what the proper way to handle this is.

Node does some [magic based on the request host headers](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L301). However, we don't have a requests per se when initiating the connection.

I guess we could do the same thing Node does and disconnect/reconnect when a new requests resolves into a different server name... not sure what the best approach is.

@mcollina any thoughts? I'm a little weak at the moment on the SSL parts. When would the `servername` and `hostname` be different? Could we default to `hostname`?

**Comment by ronag** [comment]
Probably related, https://github.com/nodejs/node/issues/28167

**Comment by mcollina** [comment]
How does Node.js treats multiple requests done with keepalive and different HOST headers?

> any thoughts? I'm a little weak at the moment on the SSL parts. When would the servername and hostname be different? Could we default to hostname? Maybe only in the case that hostname is a name and not an IP address?

I don't have any more knowldge about this topic :(.

**Comment by bnoordhuis** [comment]
> How does Node.js treats multiple requests done with keepalive and different HOST headers?

`https.Agent` creates a new connection when Host or servername changes (assuming no bugs.)

> When would the servername and hostname be different?

They're usually the same but say you want to talk to example.org but that website is hosted by cheapo.com, then it's legal for hostname=cheapo.com and servername=example.org, e.g., because example.org is a CNAME for cheapo.com.

**Comment by ronag** [comment]
@mcollina: Sounds like we should do it like Node. Which would require `Client` to defer and reconnect the socket if the hostname header changes between requests.

`Pool` and user space should probably try avoid it happening. Maybe a doc note.
